from setuptools import find_packages, setup

setup(
    name='kleio',
    packages=find_packages(exclude=("tests", "examples", "versionedzarrlib", "img")),
    version='0.2.0',
    description='KLEIO versioned Storage',
    author='Marwan Zouinkhi',
    license='MIT',
    install_requires=[
        'six>=1.16.0',
        'attrs>=21.4.0',
        'pytest>=6.2.5',
        'pluggy>=1.0.0',
        'py>=1.11.0',
        'setuptools>=65.5.0',
        'numpy>=1.23.4',
        'zarr>=2.13.3',
        'fsspec>=2022.2.0',
        'tqdm>=4.63.0',
        'dask>=2022.3.0',
        'paramiko>=2.8.1',
        'scp>=0.14.4',
        'requests>=2.27.1',
        'deprecation>=2.1.0',
        'numcodecs>=0.10.2',
    ],
    setup_requires=['pytest-runner'],
    tests_require=['pytest==6.2.5'],
    test_suite='tests',
)
